### ISSUE TITLE
Modifiers

### ISSUE THREAD

**Issue by 8bitguitarlord** [YARC-Official/YARG#166]
These are to let the players change the gameplay experience. Ex: All tap, all HOPOs, all strums, brutal mode.

**Comment by Table-JFK** [comment]
Any chance we can include "Auto Strum" and "Drunk Mode" with that list of modifiers, similar to Clone Hero?

**Comment by Pyreflyes** [comment]
What about HOPOs To Taps?

**Comment by EliteAsian123** [comment]
This has been implemented as of new engine version `a5`! Thanks for the suggestions!
