### ISSUE TITLE
Space between a UI button icon and the text that says what the given button represents is unclickable

### ISSUE THREAD

**Issue by grishhung** [YARC-Official/YARG#190]
Not sure if this is unintentional. Both the icon and the text itself are clickable, by contrast.

**Comment by EliteAsian123** [comment]
Sorry, can you give more details on where this happens? Thanks!

**Comment by EliteAsian123** [comment]
Ah, okay, I see what you mean now. Thanks!

**Comment by EliteAsian123** [comment]
Fixed a while ago, forgot to close.
