### ISSUE TITLE
nonstop scrolling up on song selection screen - (Wii Harmonix guitar)

### ISSUE THREAD

**Issue by Jimmy5651** [YARC-Official/YARG#193]
Hi. My friends and I have been playing a lot of YARG, huge fan! Thanks for all your work on it.

When running the program on my friend's steamdeck using his xbox RB controllers, we were able to play without many issues -- super fun. But when I try running YARG on my PC using my Wii RB controllers, the guitar pairs, but almost always will endlessly scroll upward on the Song Selection screen (and I can't get my drums to pair at all).

I know you must have a lot on your plate with this, but just wanted to let you know. Can't wait to keep seeing YARG develop. Thanks!

**Comment by EliteAsian123** [comment]
Thanks for the kind words! I'll have to ask @TheNathannator to take over this, as the input stuff is mostly handled by him (many thanks to him)

**Comment by TheNathannator** [comment]
Hm, that's definitely a bit odd. What did strum up and down get assigned to in the player menu when you went to map your controls?

I added some more comprehensive control mapping options recently, so if it's just not mapping the right control then you should hopefully be able to resolve that in the next version.

**Comment by Jimmy5651** [comment]
apologies for the late follow-up... the newest release seems to have solved this issue for me, thank you!

**Comment by TheNathannator** [comment]
Very nice, glad it helped!
