### ISSUE TITLE
Time signature issue

### ISSUE THREAD

**Issue by NicolasPL64** [YARC-Official/YARG#266]
[This chart](https://drive.google.com/drive/u/2/folders/10l2q5LZcFB2R97H33OshXOFbIaTXUkyE) seems to have an issue in Verse 3A with the /8 time signatures, they're ignored in-game.

**Comment by RileyTheFox** [comment]
This mid doesn't seem to have a BEATS track so I'm not 100% certain how beats are generated in that case. The midi parser follows Rock Band's format of beats by reading a BEATS track inside the mid which determines where they should be and what beats they should be, however .chart generates them at runtime. This likely won't be fixed until we migrate mid parsing to Moonscraper.

Additionally, could you perhaps convert this mid to .chart and see if the beats are what you expect? Thanks!
