### ISSUE TITLE
Vocals difficulty icon on songs not displaying accurately

### ISSUE THREAD

**Issue by Jimmy5651** [YARC-Official/YARG#277]
Hi! I just noticed with this newest release, the difficulty icon for songs isn't displaying consistently for vocals. Oftentimes songs that have vocals don't show any vox icon, sometimes it only shows the harmony icon, etc. 

Minor but makes it harder to tell which of my songs support vox, which was super easy before the latest update.

Btw this is sick. Got all my instruments binded without a problem thanks to this Mac release. Can't thank yall enough

**Comment by TheFatBastid** [comment]
Could you give a few examples of which do which?

**Comment by Jimmy5651** [comment]
sorry, just seeing this. will post some screenshots shortly

**Comment by Jimmy5651** [comment]
<img width="1440" alt="Screenshot 2023-05-18 at 10 49 17 AM" src="https://github.com/YARC-Official/YARG/assets/131910072/906b3400-15e1-439b-a62b-41e4deacd62f">
<img width="1440" alt="Screenshot 2023-05-18 at 10 49 07 AM" src="https://github.com/YARC-Official/YARG/assets/131910072/3f45fa77-57ec-4a1a-9630-19b55f244c72">
<img width="1440" alt="Screenshot 2023-05-18 at 10 48 56 AM" src="https://github.com/YARC-Official/YARG/assets/131910072/877dc5ed-1015-4c78-9390-2d8a76f1f96a">
<img width="1440" alt="Screenshot 2023-05-18 at 10 48 32 AM" src="https://github.com/YARC-Official/YARG/assets/131910072/120403ba-e30b-4943-822e-f6b95b033baf">
<img width="1440" alt="Screenshot 2023-05-18 at 10 48 16 AM" src="https://github.com/YARC-Official/YARG/assets/131910072/19c40cd1-05c7-4992-bd19-9572822d8650">
<img width="1438" alt="Screenshot 2023-05-18 at 10 47 36 AM" src="https://github.com/YARC-Official/YARG/assets/131910072/37cba61a-1a61-4f0d-9cc7-1519034cb37c">
<img width="1440" alt="Screenshot 2023-05-18 at 10 46 42 AM" src="https://github.com/YARC-Official/YARG/assets/131910072/a2d2a0a3-abbd-4f9a-a22e-85dc2b568810">
<img width="1440" alt="Screenshot 2023-05-18 at 10 46 24 AM" src="https://github.com/YARC-Official/YARG/assets/131910072/63d2ece6-f7ee-4cf1-aa1c-05badfff4156">

**Comment by TheFatBastid** [comment]
The upcoming release will fix this.
