### ISSUE TITLE
Ardwiino support

### ISSUE THREAD

**Issue by sanjay900** [YARC-Official/YARG#29]
This project looks dope!

If i were to submit a PR for adding in reactive LED support for my new firmware, would that sorta thing be merged in? 
The plan is to use HID output reports for enabling and disabling LEDs depending on game state for HID, and rumble commands for xinput. 

It would be cool to have something with proper support for this baked in, as then I have a nice way to test all these new features before I investigate modding other games.

Happy to send test firmwares your way or something if you do happen to have a arduino / pico modded guitar and want to test things yourself once it gets to that point, assuming the new firmware isn't released by the time i get around to this.

**Comment by EliteAsian123** [comment]
Hi! I'm actually aware of your work and am very impressed with it! I was talking to the creator of Polybar, and he should be sending one my way once he gets some parts.

I'm 100% towards adding proper LED support, and was actually thinking of it already. If you don't get around to making a pull request, I was probably gonna do it myself anyway once I get my hands on the Polybar. However, if you could do it, I'd be very thankful!

Thanks!

**Comment by sanjay900** [comment]
Are you planning on stagekit support as well?

**Comment by EliteAsian123** [comment]
I actually did not even know that existed! If I ever get my hands on one, I'll definitaly add support, but I'm sure on how easy they are to get.

**Comment by sanjay900** [comment]
I have ways to emulate them now as well in the next firmware release

**Comment by sanjay900** [comment]
I'm just glad you aren't using rewired because it complicates the hell out of LEDs for anything that isn't xinput

**Comment by sanjay900** [comment]
Well, this one was sorted

**Comment by TheNathannator** [comment]
Been quite the journey lol, glad to have everything supported!
