### ISSUE TITLE
v0.10.1 doesn't work on Mac

### ISSUE THREAD

**Issue by Jimmy5651** [YARC-Official/YARG#296]
<img width="255" alt="image" src="https://github.com/YARC-Official/YARG/assets/131910072/a49599b8-f18c-47b1-a706-9aa7bf9d8520">

**Comment by EliteAsian123** [comment]
Does v0.10.0 work for you?

**Comment by Jimmy5651** [comment]
Yes, was able to run the other two Mac releases.

**Comment by EliteAsian123** [comment]
Odd. I'll rebuild when I get home.
