### ISSUE TITLE
solo marker not resetting when close to another one

### ISSUE THREAD

**Issue by Doune2Sable** [YARC-Official/YARG#297]
hey, when two solo marker are close it doesn't reset the note count, which will break the percentage

https://github.com/YARC-Official/YARG/assets/133128256/901edb11-e685-42da-b3b4-b4cf5c6a1570

**Comment by RileyTheFox** [comment]
This is known and I doubt a proper fix will be made until the engine rewrite

**Comment by ClampyStew** [comment]
The solo counter will only end if after the solo marker there is no other marker, also the solo counter will only count the first solo marker (correct me if I'm wrong).

**Comment by Doune2Sable** [comment]
if by that you mean it only count the score then no, it will count the other one (i don't know if it count both) and it will give you prefect solo anyway

**Comment by EliteAsian123** [comment]
This *should* be fixed. Please reopen if not
