### ISSUE TITLE
(Roadmap) Vocals

### ISSUE THREAD

**Issue by EliteAsian123** [YARC-Official/YARG#3]
### Vocals/Mic Roadmap

- [x] Notes
  - [x] Inharmonic notes 
  - [x] Pitched/harmonic notes
  - [x] Harmony parts (multiple mics)
  - [x] Scores
- [x] Starpower
  - [x] Starpower sections
  - [x] Starpower bar
  - [x] Starpower effects
- [ ] Extras
  - [ ] Clapping (#39)

**Comment by binarygeek119** [comment]
what about tap notes is rock band songs

**Comment by EliteAsian123** [comment]
This is obsolete. Please refer to https://yarg.youtrack.cloud/agiles/147-7/current
