### ISSUE TITLE
Lyric Support for .chart files

### ISSUE THREAD

**Issue by MatharuG** [YARC-Official/YARG#305]
Hello!

After updating YARG to the latest release (v0.10.2), I was happy to see that .chart charts work just fine! (Apart for some specific situations. Example: short sustains get turned into just a note, with no sustains.)
But one thing I've noticed is that the Lyrics don't appear, unlike .mid charts of course...
If also possible (to implement), the _other rhythm game_ community made some documentation of whitelisted parameters to make rich text lyrics: https://strikeline.myjetbrains.com/youtrack/issue/CH-226
And FireFox (creator of Moonscraper) made a documentation with the .Chart properties, which was probably already looked at, but here it is anyway: https://docs.google.com/document/d/1v2v0U-9HQ5qHeccpExDOLJ5CMPZZ3QytPmAG5WF0Kzs/edit#heading=h.rsln5j98ugw0
And also, .chart Lyrics (on the _other rhythm game_) does make use of some parameters from this website: http://digitalnativestudios.com/textmeshpro/docs/rich-text/ such as <color>, <br>, and others.
I would really like to help with the project, but I have close to no expertise with coding and/or modeling, so I'm sorry...

Thank you!

**Comment by TheNathannator** [comment]
> the *other rhythm game*

You can say Clone Hero here lol, no need to worry about that.

This shouldn't be too difficult to implement, .chart support is still a WIP so it was on the todo list anyways. Rich text stuff might be ignored at first but that should also be supported eventually.

**Comment by MatharuG** [comment]
> > the _other rhythm game_
> 
> You can say Clone Hero here lol, no need to worry about that.
Yoooo drumbs! Good to see you here! Oh ok good 😅 

> This shouldn't be too difficult to implement, .chart support is still a WIP so it was on the todo list anyways. Rich text stuff might be ignored at first but that should also be supported eventually.
Oh I see. Since it's still in WIP I guess it'll take some time. About the ""short sustains"" I shortly mentioned, I think it's engine-related soooo better leave that as it is I guess...

**Comment by TheNathannator** [comment]
Yeah the sustains are cut off in-engine instead of in-parsing I think, we can also address that later down the line. Pretty much the whole game's gonna be rewritten so none of these issues are here to stay lol
