### ISSUE TITLE
v0.10.2 won't open on Mac

### ISSUE THREAD

**Issue by Jimmy5651** [YARC-Official/YARG#306]
same error message as 0.10.1, "damaged and cannot be opened"

**Comment by Jimmy5651** [comment]
Ah, just gave this command a shot in Terminal and got it to open, everything's running great now! "xattr -cr /path/to/YARG" 

Sorry for bringing that fixable issue to your attention, just found that error message strange as I was able to open v9 and v10 without it popping up. 🤷🏼‍♂️

**Comment by EliteAsian123** [comment]
All good!
