### ISSUE TITLE
[Graphics] UI is cut off on 21:9 aspect ratios

### ISSUE THREAD

**Issue by qfoxb** [YARC-Official/YARG#313]
On my 21:9 monitor, the text for the EXIT GAME button is chopped off and covered by the bottom bar.
Resolution is 3840x1600
![image](https://github.com/YARC-Official/YARG/assets/42038239/e42985e2-9793-40bf-a1f3-0b3f40627a5b)

**Comment by EliteAsian123** [comment]
Fixed in the newest version
