### ISSUE TITLE
(Question) PS3 pkg and XBOX rbcon file support?

### ISSUE THREAD

**Issue by farsdewibs0n** [YARC-Official/YARG#33]
Wondering if YARG have plans on support CON and PKG files (esp from C3)?

**Comment by farsdewibs0n** [comment]
I heard there are case of c&d on decrypting cons, but so far theres no issue on converting them to other format such as .chart/.midi for Phase Shift/Clone Hero (Onyx). So decrypting the cons is up to the users' ability, since there's a tool for it and it's closed-source. Decryption so far only exist for CON files iirc, havent found PKGs encrypted so far.

Basically if the file isnt encrypted, it should be fine (I think?)

**Comment by EliteAsian123** [comment]
Legally, it should be!

**Comment by EliteAsian123** [comment]
Xbox RB CONs are now supported!
