### ISSUE TITLE
Text stutters while scanning.

### ISSUE THREAD

**Issue by doboggio** [YARC-Official/YARG#333]
Proposed fix:

Change the lines [here](https://github.com/YARC-Official/YARG/blob/e341f1bec41b600cca9d6b2e9009c78799983570/Assets/Script/LoadingManager.cs#L92-L94C42) so that the text is left justified.

**Comment by RileyTheFox** [comment]
Very late response but this will likely not be changed unless the loading screen UI is redesigned as it is a very minor problem
