### ISSUE TITLE
Broken 5-lane drum chart conversion

### ISSUE THREAD

**Issue by TadeLn** [YARC-Official/YARG#362]
When playing a Pro Drums chart using a 5-lane drumkit, the notes aren't converted properly.
1. Visually, the conversion looks like it's working, so for example there are yellow cymbals instead of yellow toms. This still isn't exactly good, because the yellow toms should be converted to blue toms instead.
2. Gameplay-wise, even though the yellow toms look like cymbals, they still work as toms.
3. It is impossible to hit yellow cymbals. If you hit the yellow cymbal pad on the controller, it actually registers as a yellow tom. Funnily enough, you can actually still hit the yellow toms that look like the cymbals. So it just looks like you can hit some yellow cymbals but not others.

My setup: Band Hero/newer Guitar Hero 5-lane Drums for PS3, Windows 10. I can send the chart file if necessary.

**Comment by TadeLn** [comment]
Oh I just realized that there was a new update that probably fixed this issue, I didn't get to play it yet so I don't know if this issue was fixed already.

**Comment by EliteAsian123** [comment]
Yes, this should be fixed in the newest version. Please re-open this issue if it persists.
