### ISSUE TITLE
Video backgrounds loop when they end

### ISSUE THREAD

**Issue by MatharuG** [YARC-Official/YARG#374]
Hello again! Well, the title is pretty much self-explanatory, but to get into more detail: if the video background (video.mp4) is shorter than the chart, it starts over. I don't know if that is intentional or not, and that's why I'm creating an Issue.
I know video backgrounds are still very new, so I'd like to suggest two different "types" of video backgrounds: 

The ones that loop (like in CH, where they're supposed to loop, and are put in a Custom folder):
![image](https://github.com/YARC-Official/YARG/assets/26250877/d40f1726-6439-4654-9baf-54362ac4ccfc)

And the ones that don't loop (the song-specific ones.)

This could also apply to images, although that would require a priority system, such as
(Venue) > Video > Image > No BG

Once again, I don't have much experience with Unity, but I did some research and found that VideoPlayer.Unity does have a variable for looping: `videoPlayer.isLooping`.

===

While I'm at the topic of videos, I also would like to suggest for YARG to use the `video_start_time` variable that `song.ini` has, since at the moment, the videos start right away. `video_start_time` basically tells the game where to start the video (in milliseconds).
Unity has a similar "offset" variable to `video_start_time`, which is `videoPlayer.frame`, but it uses the amount of frames instead of milliseconds to define how much it skips of the video.

ok that's all, thanks!

**Comment by EliteAsian123** [comment]
Yeah, `video_start_time` is actually cached, I just keep forgetting to implement it... That's my bad.

As for the other stuff, we'll probably be implementing more advanced settings soon!

**Comment by TheNathannator** [comment]
This issue has been fixed for a while now, apologies for the delay!

- Global backgrounds will always loop.
- Song-specific video backgrounds will *not* loop if a video start/end time (other than 0 and <= 0 respectively) is specified, otherwise it will loop if its length is less than 85% of the song's.
