### ISSUE TITLE
Camera moving when activating Overdrive after changing camera angle mid-song

### ISSUE THREAD

**Issue by Katero410** [YARC-Official/YARG#377]
Hey there!
I noticed when playing around with the camera settings that there is a bug when you change the settings while in a song.

In the video below you can see that the first overdrive activation is normal, when the camera settings were changed before starting the song.
But after changing the settings a bit and activating overdrive again, the camera jumps away weirdly and stays like that until the end of the song or if the settings are changed again. But if you activate overdrive after "correcting" the error, it'll jump away again. After the song the camera stays as intended.

https://github.com/YARC-Official/YARG/assets/40720544/62dae04f-de73-4941-9911-3ccf564b4354

The angle the camera gets set to seems to depend on what the player set the settings to. I've also had tries where the camera gets set really close to the highway instead of far away, but I'm not exactly sure how the two correspond.

Playing on YARG v0.10.4 Windows 10

Hope this can/ will be fixed somehow, really like the feature of being able to adjust the angle of the highway! ❤️
Thanks!

**Comment by EliteAsian123** [comment]
Hi, I think this is *only* an issue when editing the settings in game, so it should be fine if you restart the song, or back out and go back in. I plan to fix this soon, and apologies for the inconvenience!

**Comment by TheNathannator** [comment]
This issue has been fixed since v0.12, where camera settings are now per-player (though no longer editable during gameplay).
