### ISSUE TITLE
Cannot navigate song selection menu with the keyboard if strum up/down are assigned to letter keys

### ISSUE THREAD

**Issue by fernandoGubiMarques** [YARC-Official/YARG#378]
I assign Q and W as the strumming keys when I play on keyboard. However, in the song selection menu, if you start typing letter characters, your input goes straight to the search bar, making it impossible to navigate.

This only happens after you're done playing a song and are dropped back in the song selection menu, not when you access it from the main menu, so my current workaround is returning to the main menu and then entering quickplay again.

**Comment by EliteAsian123** [comment]
Oh good point, thanks for pointing this out. Apologies for the inconvienece!

**Comment by EliteAsian123** [comment]
Fixed in #396
