### ISSUE TITLE
iPhone not working as microphone on 10.4

### ISSUE THREAD

**Issue by Jimmy5651** [YARC-Official/YARG#390]
Hi! Just noticed that when I add a new player and select my iPhone as my microphone, songs will not load -- just a black screen and the wheel of death when I try to play one. This definitely worked for me prior to 10.4 (running Mac version btw).

Just lettin yall know. Would be a sick feature to have if the boys are over and trying to sing some harmonies -- yknow, guy stuff. Thank you! 🙏

**Comment by EliteAsian123** [comment]
Hi, can you send the log files?
