### ISSUE TITLE
(Roadmap) Pro-Guitar

### ISSUE THREAD

**Issue by EliteAsian123** [YARC-Official/YARG#4]
### Pro-Fret Guitar Roadmap

- [ ] Notes
  - [x] Normal notes 
  - [ ] Sustain notes (almost there)
  - [ ] HOPO notes
  - [ ] Slide notes
  - [x] Scores
- [x] Starpower
  - [x] Starpower sections
  - [x] Starpower bar
  - [x] Starpower effects
- [ ] Extras
  - [ ] Guitar solos
  - [ ] Big rock endings
- [ ] Difficulty downsampling
  - [ ] Easy
  - [ ] Medium
  - [ ] Hard 
- [ ] Controllers
  - [ ] #16

**Comment by raphaelgoulart** [comment]
Please add "arpeggio markers" somewhere, as they're missing and are misread as chords
- How they currently look: https://cdn.discordapp.com/attachments/1086048857714069519/1101945693410693150/Untitled.mp4
- What they actually look like: https://youtu.be/EUPixCcu8QM?t=95

**Comment by EliteAsian123** [comment]
This is obsolete. Please refer to https://yarg.youtrack.cloud/agiles/147-7/current
