### ISSUE TITLE
Game is opening in 4:3

### ISSUE THREAD

**Issue by qfoxb** [YARC-Official/YARG#426]
I have YARG set to exclusive fullscreen, game always starts in 4:3, Only fix is to press Alt+Enter Twice.
Only started appearing in 0.10.5
![image](https://github.com/YARC-Official/YARG/assets/42038239/44558784-c210-4d98-84c6-6d8e75fef7c7)

**Comment by CloneHeroUruguay** [comment]
Yup, same thing happened to me. Resolution was set automatically to "Highest possible".

**Comment by EliteAsian123** [comment]
Fixed in #427, and should be out in the next patch
