### ISSUE TITLE
What is the "source" tag?

### ISSUE THREAD

**Issue by CloneHeroUruguay** [YARC-Official/YARG#429]
I want to know what is that under "play song" on the song list menu. It's set to "uknown source" because I didn't write any source, I suppose. But I don't know where or how to modify that, or even what it is.

I tried checking out the documentation made by The Nathannator but no luck finding a "source" tag... maybe I missed it.

**Comment by RileyTheFox** [comment]
To add onto this, the source is inferred from the icon tag in an ini song. For example, icon=cth3 would set the source to Carpal Tunnel Hero 3
