### ISSUE TITLE
Discord Rich Presence not displaying remaining song time properly

### ISSUE THREAD

**Issue by qfoxb** [YARC-Official/YARG#435]
Discord rich presence is not detecting the proper time remaining in a song, resulting in it saying anywhere from 1 minute to 1 second remaining when the song starts.
![image](https://github.com/YARC-Official/YARG/assets/42038239/b4ba035b-8afa-4491-8735-7e03db830917)

**Comment by EliteAsian123** [comment]
Hmm, this is odd. I *think* it should be fixed by now, but please reopen if not.
