### ISSUE TITLE
Song can't be played on vocals after a "percussion section" appears

### ISSUE THREAD

**Issue by SkullMan140** [YARC-Official/YARG#436]
just tried playing "Working for the Weekend" and noticed the song is literally unplayable on vocals after the 1st percussion section that appear originally in the chart in the RB titles

also tried with other songs that have a percussion section and the rest of the song is unplayable after that section ends, don't matter if you sing in-tune, the song don't work properly anymore

**Comment by EliteAsian123** [comment]
Yes, this is known and should be fixed in a patch tonight. Apologies for the inconvience!

**Comment by SkullMan140** [comment]
> Yes, this is known and should be fixed in a patch tonight. Apologies for the inconvience!

no problem, happy to help and see this game grow :D

**Comment by EliteAsian123** [comment]
Released! Please reopen if it persists.
