### ISSUE TITLE
video_start_time not working

### ISSUE THREAD

**Issue by YovaniDosSantos** [YARC-Official/YARG#476]
I could be doing this wrong but I don't think I am. I'm using all my songs from CH that have videos and (video_start_time) that are set to my liking but their not registering in YARG. I don't know if theres a ingame option or if it's something I have to change in the song ini that is specific to YARG. Any help would be much appreciated.

**Comment by EliteAsian123** [comment]
I believe this should be fixed in the bleeding edge build. Can you test it out there and let me know?

**Comment by YovaniDosSantos** [comment]
I guess I should have looked more into it, I thought there was only 1 type of build. After downloading the BE Build it works without a problem. Much appreciated.

**Comment by EliteAsian123** [comment]
Awesome, glad to hear!
