### ISSUE TITLE
Where the BassNative plugin comes from?

### ISSUE THREAD

**Issue by ebellumat** [YARC-Official/YARG#478]
Hello, i'm working porting this game to Android, but the BassNative plugin folder don't have files for Android.

Wheres this plugin come from?

How to fix? The game won't start because the missing files on Android.

**Comment by EliteAsian123** [comment]
`install.py` automatically downloads for Windows, Mac, and Linux from [here](https://www.un4seen.com/). BASS does have an android build on the same website.

Hope this helps!

**Comment by RileyTheFox** [comment]
Specifically you will need the following libraries for Android:

BASS
BASS_FX
BASSmix
BASSOPUS

**Comment by ebellumat** [comment]
I found the libraries for Android, https://www.un4seen.com/files/bass24-android.zip, but the code looks harcoded to load the windows version of the dll hard coded. 

![image](https://github.com/YARC-Official/YARG/assets/26942680/e4f5a642-1a61-4522-ab9b-45c5eee93b1c)

On Linux, the name of the file is libbassopus, i have to change this as well? Or this line of code is smart enough to resolve the path? 

Thanks for the help!

**Comment by RileyTheFox** [comment]
> On Linux, the name of the file is libbassopus, not bassopus, i have to change this as well? Or this line of code is smart enough to resolve the path?

Hmm that seems like a small oversight on my part. I can fix this up soon, nobody has actually ever reported a problem with opus not loading on Mac/Linux. If you want to test with Android, you can just hardcode the android file name instead for now.

Bear in mind you will also need to modify the `GetBassDirectory()` function to include a clause to get the Android plugins folder when compiled. I don't know the folder structure of a Unity game for Android so this is something you'll need to figure out yourself.

I have a PR open for some changes regarding the BASS libs to fix an issue with MOGG channels, so I will make the opus loading fixes on that before it is merged. After that merge, we are going to be using a special update of BASS provided to us by the developer to fix some channel panning issues, and we won't have an Android version for that. It's only a very minor problem which affects a small number of songs, so it shouldn't be an issue.

Also just to note I don't think we will ever be including the Android builds of BASS in the repo, as we don't currently have any plans to officially support it. Building for Android can have a lot of differences and situations you need to handle compared to Windows/Mac/Linux and it isn't something we are interested in officially doing. You are of course free to make your own Android builds on a fork.

**Comment by ebellumat** [comment]
Thank you for the help! For Android some things are more complicated, take a quick look on the folder structure of the bassopus lib, so, i think i have to tweek GetBassDirectory a little more, 4 archs at once, insane thing haha. 

I'm creating a touch based Android version to prepare the project to be a VR Version of Yarg! Wish me luck! 

 ![image](https://github.com/YARC-Official/YARG/assets/26942680/42f688d6-718d-4701-b561-bad19f5e69b5)
![image](https://github.com/YARC-Official/YARG/assets/26942680/171fedbb-1933-4f36-81ec-9530efa292ae)

**Comment by RileyTheFox** [comment]
Update: I looked at the ManagedBass wrapper source and it will attempt to find "libbassopus" even if I put in "bassopus"
![image](https://github.com/YARC-Official/YARG/assets/29326764/a482417f-278b-49a9-b7db-260790d5e83f)

So the plugin will be loaded correctly no matter what
