### ISSUE TITLE
Pro Drums from .chart format disables StarPower

### ISSUE THREAD

**Issue by eckerj** [YARC-Official/YARG#488]
I recently commissioned a song for drums and was provided a .chart file from the charter.  When I attempt to play the song with a Pro Drums Bot in 0.10.7, there are no StarPower/OverDrive phrases/events.  When playing the same song on just plain ol' 4-Lane drums, the StarPower/OverDrive phrases/events show up.

I verified the issue happens with any .chart format song containing a drum track while playing Pro Drums.

I did browse through the code and the parser **appears** to load the starpower events, but I quickly became lost after that.

**Comment by TheNathannator** [comment]
Yeah we're not quite sure why this happens yet, it *should* be working fine but it's not. Haven't gotten a chance to debug properly yet.

**Comment by eckerj** [comment]
Verified this was fixed in v0.11.0 ! yay!

Thanks much!
