### ISSUE TITLE
MacOS version has overheating issues (only tested on M2)

### ISSUE THREAD

**Issue by rilinium** [YARC-Official/YARG#503]
Device: MacBook Air M2 13
MacOS: Ventura 13.4.1
YARG: v0.10.7
Temps (Idle): 32 Celsius
Temps (YARG): 90-96 Celsius

I don't believe this is a hardware problem since not even benchmarks will make the temps go this high

**Comment by EliteAsian123** [comment]
Hi, thanks for reporting this issue. What is your FPS cap? Do you have VSync on?

**Comment by rilinium** [comment]
FPS is capped to 60, Vsync enabled

**Comment by rilinium** [comment]
This appears to have been fixed in the macOS Sonoma Beta, no clue why exactly

**Comment by EliteAsian123** [comment]
Hmm okay... I'm going to close this for now then.
