### ISSUE TITLE
wrong note count in solo sections

### ISSUE THREAD

**Issue by pablo5425** [YARC-Official/YARG#507]
solo sections display a wrong amount of notes. this is a chart im making and i know it has 59 notes
![image](https://github.com/YARC-Official/YARG/assets/34631489/78fc0f0c-9a07-4073-84ee-7031515d662e)
i think its counting chords as several notes instead of just one

**Comment by EliteAsian123** [comment]
Fixed in 83dda42d2d69d89a86306f4acc8eb01f26967bf2. Thanks!
