### ISSUE TITLE
3D mode

### ISSUE THREAD

**Issue by binarygeek119** [YARC-Official/YARG#510]
i have my computer hooked up to a 3D projector would be cool to be able to use that.

there are a few types of 3D modes.

### 
Side-by-Side 3D
In Side by Side 3D format, one frame is divided into left and right two sub-frames, with the entire frame for the left eye scaled down horizontally to fit the left-half of the frame, and the entire frame for the right eye scaled down horizontally to fit the right side of the frame.

The difference between Side by Side (Half-Width) and Side by Side (Full)

For instance, you have a 1080p (resolution of 1920×1080) source video.

If you choose the Side by Side (Half-Width), the output video frame for the left/right eye will be at a 810×1080 resolution, and the resolution of the output video will be 1920×1080.

If you choose the Side by Side (Full), the output video frame for the left/right eye will be at a 1920×1080 resolution, which means the resolution of the output video will be 3840×1080.

So please make sure if the output video resolution is suitable for your device before you choose the Side by Side (Full) as the output 3D mode.

### Top-and-Bottom 3D
In the Top and Bottom 3D format, one video frame is divided into two sub-frames, the upper one consisting of the sub-frame meant for the left eye and the lower sub-frame meant for the right eye.

The difference between Top and Bottom (Half-Height) and Top and Bottom (Full)

For instance, you have a 1080p (resolution of 1920×1080) source video.

If you choose the Top and Bottom (Half), the output video frame for the left/right eye will be at a 1920×540 resolution, and the resolution of the output video will be 1920×1080.

If you choose the Top and Bottom (Full), the output video frame for the left/right eye will be at a 1920×1080 resolution, which means the resolution of the output video will be 1920×2160.

So please make sure if the output video resolution is suitable for your device before you choose the Top and Bottom (Full) as the output 3D mode.

### Anaglyph Red/Cyan 3D
Anaglyph Red/Cyan 3D was the earliest method of presenting 3D effect and it requires less technology and specialized hardware.

In an Anaglyph 3D video, the two images are superimposed in an additive light setting through two filters, for example one red and one cyan. In a subtractive light setting, the two images are printed in the same complementary colors on white paper. Glasses with colored filters in each eye separate the appropriate images by canceling the filter color out and rendering the complementary color black.

Tipard will provide you up to 10 Anaglyph 3D modes like Red/Cyan, Green/Magenta, and Amber/Blue, (monochrome / half color / full color / high quality Dubois).

You don't need other special hardware or software, only a pair of archetypical 3-D glasses will enbale you to watch a Anaglyph Red/Cyan 3D video. You can play the video on a common computer with common media player software, or watch it on common TV.

### gameplay

be about the same but the highway would appear to come at you. and maybe a bit more tilt to it.
there could also be more FX coming at you when accomplished tasks

there could also help if you go for VR support.

**Comment by EliteAsian123** [comment]
This kind of thing is definitely a *far* future sort of thing, unfortunately, so I will be closing the issue for now. Thanks for the suggestion!
