### ISSUE TITLE
Does not apply "delay" in song.ini

### ISSUE THREAD

**Issue by seetart** [YARC-Official/YARG#512]
When playing a song that has "delay = [whatever in milliseconds]" in the song.ini, the delay will not be applied to the song when playing causing the song to be out of sink.  Songs without a delay value or delay set to 0 work fine (as they should).   

Attached two song files:
Critical Acclaim has no delay and is fine
Tragic Kingdom has a delay set, so when the song loads in game it is out of sync

[Avenged Sevenfold - Critical Acclaim.zip](https://github.com/YARC-Official/YARG/files/11932705/Avenged.Sevenfold.-.Critical.Acclaim.zip)
[No Doubt - Tragic Kingdom.zip](https://github.com/YARC-Official/YARG/files/11932709/No.Doubt.-.Tragic.Kingdom.zip)

**Comment by EliteAsian123** [comment]
This has been fixed in the new engine version of the game, and will be fixed once the new engine releases in stable! Thanks for the report!
