### ISSUE TITLE
Release zips have the tarbomb problem

### ISSUE THREAD

**Issue by Soundtoxin** [YARC-Official/YARG#517]
https://en.wikipedia.org/wiki/Tar_(computing)#Tarbomb

The problem: The release zip contains a bunch of "loose files" which will litter the current directory, be hard to keep track of, and can overwrite other files with the same name.

The solution: Create a directory inside the release zip files that holds all of this stuff so that if someone were to run `unzip YARG_v0.10.7-Linux-x86_64.zip` or similar, they would just get one new file, a directory containing all the stuff from the release, instead of several files. This new directory could be named the same as the release zip, like `YARG_v0.10.7-Linux-x86_64`, or it could just be something generic like `YARG`.

There are *workarounds* to this issue implemented in stuff like 7zip where you can extract an archive to a new directory with the same name as the archive, but having to do this is not ideal, and this is not as trivial to do from the command line. You also need to know you're dealing with a tarbomb to know to do that instead of something like the "extract here" right click options, which would give you the same problem as unzipping from the CLI.

**Comment by EliteAsian123** [comment]
With the launcher coming up, it's kinda "too late now," because we'd have to rezip *every single update on every single platform*. With it however, this isn't something that you'll have to worry about. Apologies for the inconvenience!

**Comment by Soundtoxin** [comment]
I wouldn't expect you to fix old releases if that's what you mean, just the new ones. Or are you saying that the launcher is going to use these zips and expects them the way they are? I imagine you could automate redoing all the zip files if needed rather than doing it by hand.

Is there somewhere I can read more about how the launcher is planned to work? I guess maybe you'd download one executable instead of an archive and then it would handle grabbing the rest of the game files over the internet or something. If that's how it worked it might be worse for portability in scenarios with no network connection, like throwing the files on a flash drive to easily set up on another machine wherever you are.

**Comment by EliteAsian123** [comment]
Portable versions of YARG will still be available, however, stuff like the setlist can only be downloaded through the launcher for security, and in the future, the launcher will probably be a requirement to prevent cheating when leaderboards are added.

You can see the launcher [here](https://github.com/YARC-Official/YARC-Launcher) at its current state.
