### ISSUE TITLE
Broken symlinks break song scanning

### ISSUE THREAD

**Issue by TadeLn** [YARC-Official/YARG#522]
If there is a broken symlink somewhere in the song directory, the search will stop prematurely, missing some of the songs.

Here is an example:
![Screenshot 1](https://github.com/YARC-Official/YARG/assets/45140604/45fc8378-157f-4a23-afb3-a02f19216d09)

The above directory structure gives 7 songs when scanned (the `dontforget` song is not being detected)
![Screenshot 2](https://github.com/YARC-Official/YARG/assets/45140604/37e95af5-122d-42aa-9c2a-925a5c45ce8c)

Removing the broken symlink like so:
![Screenshot 3](https://github.com/YARC-Official/YARG/assets/45140604/58811965-7ae4-45af-92ff-ec8423a612ad)

fixes the issue, and now there are 8 songs.
![Screenshot 4](https://github.com/YARC-Official/YARG/assets/45140604/731dcd42-6003-4bd6-9a39-43e76817b71f)

Any other kind of file, and even non-broken symlinks work just fine, but symlinks that lead to nowhere seem to break something in the scanning code.

**Additional information:**
OS: Linux, Debian (but it may also affect Windows, unsure)
YARG Version: v0.10.7

**Expected behavior:** the `dontforget` song loads regardless of the presence of broken symlinks

**Comment by RileyTheFox** [comment]
Are there any error logs associated with this issue?

**Comment by TadeLn** [comment]
The badsongs.txt file is empty and there is no stdout/stderr output apart from the unity bootup stuff. Are there any other log files that I should check?

**Comment by TheNathannator** [comment]
Unity generates a log file in `~/.config/unity3d/YARC/YARG`, if there's an exception being thrown then it'll be logged there.

**Comment by TadeLn** [comment]
Here is the log file: 
[Player.log](https://github.com/YARC-Official/YARG/files/12031243/Player.log)

And also, here is what looks like the relevant part of it:
```
Performing full scan
Scanning folder: /home/tadeln/Nextcloud/public/clone_hero/songs
FileNotFoundException: Could not find file "/home/tadeln/Nextcloud/public/clone_hero/songs/Deltarune/a_broken_symlink"
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <a01111b1273a40cc8673b44832e8a221>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean isAsync, System.Boolean anonymous) [0x00000] in <a01111b1273a40cc8673b44832e8a221>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) [0x00000] in <a01111b1273a40cc8673b44832e8a221>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess)
  at XboxSTFS.XboxSTFSFile.LoadCON (System.String filename) [0x00007] in <f836d902531846fa8a530223a205c40f>:0 
  at YARG.Song.SongScanThread.ScanSubDirectory (System.String cacheFolder, System.String subDir, System.Collections.Generic.ICollection`1[T] songs) [0x0022a] in <f836d902531846fa8a530223a205c40f>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
YARG.Song.SongScanThread:ScanSubDirectory(String, String, ICollection`1)
YARG.Song.SongScanThread:ScanSubDirectory(String, String, ICollection`1)
YARG.Song.SongScanThread:FullScan()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Finished scanning /home/tadeln/Nextcloud/public/clone_hero/songs, writing cache
Wrote cache
Finished Scanning.
Writing badsongs.txt
Finished writing badsongs.txt
```

**Comment by RileyTheFox** [comment]
Hmm it seems to be happening when trying to read a CON file. So I think the code is assuming the symlink is a CON and trying to read it.

We're making plans to redesign the scanning process from scratch to resolve a lot of problems and make it easier to work with, so symlinks is something we can keep in mind when doing that!

There isn't much we will do currently to fix this as we're going through with a big rewrite of large parts of the game so I'll close this and will keep it in mind while redesigning the scanning stuff
