### ISSUE TITLE
Chart files don't display lyrics correctly if phrase start and lyric events occur at the same time.  

### ISSUE THREAD

**Issue by fernandoGubiMarques** [YARC-Official/YARG#523]
I came across a chart in which the first syllable of all lyric phrases were missing.

Upon inspecting the .chart file, I noticed the phrase_start events happened at the same time as the first syllable of each phrase, probably because they were added in by some script, as this is a very strange charting practice.

**Comment by TheNathannator** [comment]
This should be fixed in v0.12, if it's not feel free to re-open!
