### ISSUE TITLE
Disabling Starpower SFX in pause menu while Starpower is in use will cause the Starpower SFX to linger on, even after the Starpower runs out, instead of disabling the effect.

### ISSUE THREAD

**Issue by KanaiZo** [YARC-Official/YARG#532]
Starpower SFX as in the reverb effect added to the track.
Video example:

https://github.com/YARC-Official/YARG/assets/70113079/98fd49d5-2c70-4bd1-9980-d1699894ab21

**Comment by TheNathannator** [comment]
Technically no longer an issue in v0.12, settings are no longer configurable during gameplay currently. (The option to disable the SP effects also hasn't been re-implemented yet.)
