### ISSUE TITLE
Multiple inputs for a single action

### ISSUE THREAD

**Issue by Yattabyte** [YARC-Official/YARG#536]
At least on the drums, it would be nice to map multiple inputs to the same action. For example, there are some electric drums kits that have a sensor in the rim, such as on the snare. In that example, mapping both the pad and the rim to the snare-hit action is sometimes helpful. I personally don't need this, but a buddy of mine with the same kit prefers this.

**Comment by RileyTheFox** [comment]
This is already addressed in the engine rewrite we're doing, which we're hoping to release a test build for in less than a week!

**Comment by Yattabyte** [comment]
🙌
