### ISSUE TITLE
[0.12.0 Alpha 2] (Visual Bug) Infinite Starpower & Endless Solo

### ISSUE THREAD

**Issue by sh0ckR6** [YARC-Official/YARG#545]
I was trying out the new alpha engine earlier today and ended up with infinite starpower and an endless solo. After looking over it again, the infinite starpower was just visual and the supposed starpower multiplier wasn't being applied.

Not sure if there's a better place to be submitting this (somewhere in the Discord or another repo), but would be more than happy to move this issue somewhere else if needed!

#### Relevant Footage
<img width=512 height=288 src="https://github.com/YARC-Official/YARG/assets/68568464/8effcecc-dce1-4a60-81d8-125221aac3fd" />

[Full Recording (Twitch VOD)](https://www.twitch.tv/videos/1898298876)

#### Logs
[Session Log (ending after bugged song)](https://github.com/YARC-Official/YARG/files/12331345/bug-Player.truncated.log)
[Full session log](https://github.com/YARC-Official/YARG/files/12331348/Player.log)

**Comment by EliteAsian123** [comment]
I believe these have been fixed as of the newer alphas. Please reopen if it persists!
