### ISSUE TITLE
More of a question: Is it fine if I use the songs I used in clone hero as long I don't share them?

### ISSUE THREAD

**Issue by TheClaudeQC** [YARC-Official/YARG#547]
I am not so sure if I could keep all my songs I used in clone hero, I would be happy if I could as a personnal use.

**Comment by TheNathannator** [comment]
We don't (and can't) regulate the songs you use in YARG. We just support the formats, and (for legal reasons) don't condone piracy.

In the future, questions like this would be best asked in our Discord, you can find it [here](https://discord.gg/sqpu4R552r) or by clicking the Discord icon in the [readme](https://github.com/YARC-Official/YARG#readme).
