### ISSUE TITLE
New notes?

### ISSUE THREAD

**Issue by Boba194230** [YARC-Official/YARG#549]
Any way that we could get an option that changes the notes from rock band style to more of a guitar hero style like clone hero? I understand if it’s too hard but the rock band notes are a bit hard for me to read for hopos and cymbal notes. Honestly if it could be a per profile that would be pretty cool but I’d be fine with a game wide setting as well. I love this project since I can finally sing Karaoke style to some of my favorite songs, but I can’t make the full switch from clone hero yet because of the notes messing with my playability for guitar and drums.

**Comment by TheNathannator** [comment]
Themes and noteskins and such are planned, but it'll be quite some time before anything gets implemented for real. We're still busy rewriting basically the entire game lol, need to finish that first.

**Comment by Boba194230** [comment]
No problem, awesome to hear that it's being planned. Good luck!
