### ISSUE TITLE
Noise cancellation on mic

### ISSUE THREAD

**Issue by farsdewibs0n** [YARC-Official/YARG#550]
My pic picks up sound my pc fan ingame. tried turning down the mic volume, makes overdrive activation harder

Wondering if noise cancellation is planned.
Or maybe a noise gate feature (like in OBS)

**Comment by EliteAsian123** [comment]
Thanks for the suggestion! Noise cancellation is quite complicated, however, there are services like Krisp that make it possible that can be installed on the user's end. The only thing we can really offer is the mic sensitivity unfortunately, and the overdrive activation for vocals have been overhauled in the new engine.
