### ISSUE TITLE
Full Combo animation on 0%

### ISSUE THREAD

**Issue by DJkefo** [YARC-Official/YARG#552]
I just realized this when playing a bit, I had a player bound to my keyboard and another to Midi and selected the same settings for both and only played on the Midi player. After the song was over, the player that didn't play (and so got 0%) got the animation for if you get a full combo. 

Tl:Dr if you hit 0% of the notes in a song, you still get the full combo animation, even though you hit nothing

**Comment by RileyTheFox** [comment]
Fixed as of rewrite/new engine
