### ISSUE TITLE
Don't start with the search bar active

### ISSUE THREAD

**Issue by MetaNite64** [YARC-Official/YARG#554]
...at the very least, for keyboard players ;>
When playing on a keyboard, menu inputs also type into the search bar at the same time. You have to click off of the search bar to disable this, and you have to do this every time you go back into the song list. It would be nice for this to not happen by default, and ideally for clicking on the search bar to temporarily disable menu inputs as well. I recognize the utility of having this happen if you're playing with a controller, so maybe this could be only a change for people with keyboard input, or perhaps a toggle in the settings.

**Comment by EliteAsian123** [comment]
Hi, thanks for the issue report! This was fixed in [this commit](https://github.com/YARC-Official/YARG/commit/162099c97c97c44122b0617d6d5ecdca9a43941c) and will be released in the next update! Thanks!
