### ISSUE TITLE
Long note threshold

### ISSUE THREAD

**Issue by CrowMash** [YARC-Official/YARG#555]
I just played YARG yesterday and first of all congrats on making this, it works very weel even on early stages of development.

I noticed that if you don't play 100% of a long note the sound of this note is cut. I remember that on Rock Band if you play like ~95% of that note and play an other one after, the music is not cut. Sometimes it's really hard to move to the next note without cutting the end of the long one and it's a bit frustrating.

**Comment by RileyTheFox** [comment]
Should be fixed as of new nightly today with the re-implementation of guitar sustains and sustain bursts.
