### ISSUE TITLE
[feat] Better Discord RPC for New Engine

### ISSUE THREAD

**Issue by BurAndBY** [YARC-Official/YARG#590]
Currently the RPC for New Engine looks unused. 

![image](https://github.com/YARC-Official/YARG/assets/48630651/03c96ada-928f-4bfa-850b-e39893db511a)

Idea is to make Discord RPC change on song load, profile edit etc.

# Mockups 
I didn't find the logo, but that shows what I mean

![image](https://github.com/YARC-Official/YARG/assets/48630651/14d94ffe-f160-49e7-9b52-63b7f6c63ea2)
![image](https://github.com/YARC-Official/YARG/assets/48630651/83f17730-07eb-4a40-8d19-1442e1c3a2a9)
![image](https://github.com/YARC-Official/YARG/assets/48630651/694b4bc3-d262-488a-a1f3-67294f09b597)

**Comment by BurAndBY** [comment]
P.S.: This is very low priority

**Comment by RileyTheFox** [comment]
This has been partially implemented recently in v0.12.1. Current song is displayed with elapsed time and album cover support.
