### ISSUE TITLE
HOPO Automatic 'Strum'

### ISSUE THREAD

**Issue by axemonk** [YARC-Official/YARG#593]
Version - 0.12.0-a7

Song - Burden In My Hand - Soundgarden - Official Harmonix Chart (RB3 DLC)

This hammer-on note activates itself without any input other than continuing to hold the two frets for a previous note.

This behavior is unaffected by the Anit-Ghosting setting.

I'll update this if I find other examples, but here's one:

https://github.com/YARC-Official/YARG/assets/17395305/7ffa5687-79fd-423d-8529-26cfffd8e6e0

**Comment by EliteAsian123** [comment]
Yes, I believe this is intentional. I believe the reason was to make double notes with HOPOs on the second a lot more sane to hit. I'm not sure of the time window for that, but it can be adjusted if needed.

**Comment by RileyTheFox** [comment]
Fully intentional feature. Won't be changed
