### ISSUE TITLE
[Nightly] Buttons held on a pause will remain held until pressed again

### ISSUE THREAD

**Issue by yoitsOJ** [YARC-Official/YARG#634]
In both practice and quickplay, on both square and circle theme, if you hold frets while pausing, those buttons will remain held after unpausing until they are pressed again

Clips:
[Practice, Circle Theme](https://youtu.be/9IZYRuEmSTo)
[Practice, Square Theme](https://youtu.be/C2yBxQEZO-M)
[Quickplay, Square Theme](https://youtu.be/Jl6uzNVHdQg)

It's not just cosmetic, they're functionally held down too. You can see in this clip I can't hit the gr/gy (or i guess ro/ry) chords (I strummed them too, not a ghosting problem), but I did hit that r/b (or o/g) chord at the end even though I wasn't holding blue(green), just red(orange).

[Evidence of functionality](https://youtu.be/9HAURnzuzY0)

(sorry I didn't have a hand cam set up or anything, just trust me I promise I wasn't holding the buttons lol)

**Comment by yoitsOJ** [comment]
I don't think the fact it's Windows matters much lol, seem like predominantly a game issue

**Comment by TheNathannator** [comment]
This is a known issue, it's because inputs are not forwarded to the engine while paused, so any fret releases that occur aren't processed. Surprisingly wasn't on our issue tracker yet, [added it here](https://yarg.youtrack.cloud/issue/YARG-114).

**Comment by TheNathannator** [comment]
This issue has now been fixed for a good bit, apologies for the late response!

**Comment by yoitsOJ** [comment]
No problem lol, good that it’s fixed.
