### ISSUE TITLE
[Nightly] Vocal Score not added to full bad score

### ISSUE THREAD

**Issue by Crono141** [YARC-Official/YARG#635]
Hey all. Just got YARG set up on my windows 10 PC, hooked up my midi pro for xbox adapter and a couple of mics and started testing out. So far everything seems great/fine, except in the nightly the vocals score isn't added to the full bad score.  Vocals ARE scored, as they show up in the after track summary, but only my drum score was counted toward the full band score. I tried a different track earlier today as well on just vocals, and the song ended with 0 band points even though individual instrument score for vocals was present and non-zero. Searched opened and closed issues and didn't see it, so I thought I'd report. Let me know any other info you might need to troubleshoot this.  Thanks.

**Comment by EliteAsian123** [comment]
Thanks for the report! Fixed in fb6ab5e3a8131ef6724312bb836296aa0ae57719.
