### ISSUE TITLE
Clarify upgrade process for portable version

### ISSUE THREAD

**Issue by Soundtoxin** [YARC-Official/YARG#643]
If I already have the game installed with songs in it and such, how am I intended to upgrade to the new version? Can I just drag and drop the files from the new archive into the old spot, overwriting as needed? Or do I delete what I had minus the songs and drop in the new files alone? But then I assume I'd lose saved bindings and such, not sure where those are stored. The README seems to only describe how to do the initial install and not what to do when a new version comes out. I know you're encouraging launcher use, but I don't think everyone wants to use the launcher or is even able to use the launcher in all cases, so would be nice to know how to handle upgrades without it.

**Comment by Soundtoxin** [comment]
I tried just dragging and dropping the new files to overwrite the old ones and it seemed to work as far as I could tell, but not sure if that was a good idea or not. I may not have had any saved players already (not even sure if those can stay saved yet) so not sure if those settings were preserved, but I still had an old high score for a song saved.

**Comment by EliteAsian123** [comment]
Yes, you can just replace the files. Settings are stored in persistent data paths, so you're all good!
