### ISSUE TITLE
Add New Device button seems to do nothing in Nightly (confusing UX?)

### ISSUE THREAD

**Issue by Soundtoxin** [YARC-Official/YARG#651]
I tried on two machines, one Windows, one SteamOS. I add a new profile, select standard drums, scroll down, click Add New Device. Nothing. I keep clicking in different spots in case I'm missing some small low-contrast target. The game detected my controller at launch so I'm not sure what's going on here. I've never had issues adding my controller in Stable, but the UI is totally different there, so maybe I'm just doing something wrong (which is still probably a sign of bad UX).
Okay, I tried a little harder right before I was gonna post this and I noticed there was a small "Connect" button on the left. Clicking that brought up a device menu and worked. So, what is the Add New Device thing on the right side even for?

**Comment by RileyTheFox** [comment]
It adds a new device to an already connected profile. It's for connecting multiple devices to one profile, such as a guitar and keyboard. Or guitar and foot pedal

**Comment by Soundtoxin** [comment]
Thanks for that info. I think it could/should be made more obvious how to connect your initial controller, either combining these into one area or somehow making the connect button more obvious. I know now, so I'll probably be good even with it where it is, but I think it could be a problem for other new users.

**Comment by RileyTheFox** [comment]
Closing this as the UI has been altered to not show the profile settings until it has been connected. Should help with some of the UX issues.
