### ISSUE TITLE
Feature Request: Song Progress Indicator

### ISSUE THREAD

**Issue by Soundtoxin** [YARC-Official/YARG#652]
I'm glad the elapsed time in the song is shown in the Nightly, but it would be nice to also see the total length next to it and maybe a moving bar [sorta like what osu! has](https://i.ytimg.com/vi/-Alpf4wSY_I/maxresdefault.jpg) at the edge of the screen to just give an idea of how close to the end of the song you are. Sometimes I find myself thinking "I'm getting tired, is this song almost over?" but there's not an easy way to know.

**Comment by kaduwaengertner** [comment]
![image](https://github.com/YARC-Official/YARG/assets/87105274/2b34c690-9c5c-448c-878b-bef903a4e818)
![image](https://github.com/YARC-Official/YARG/assets/87105274/10e2ab3a-5038-49cf-ad47-97059618b214)

Both are already possible on Nightly

**Comment by Soundtoxin** [comment]
Thank you. Found it under Graphics settings. Didn't think it'd be configurable. Very cool. The graphical progress on score box is quite subtle so I had to go play a song to see what that looked like, didn't realize it was there before. I would've hoped for a line across the whole screen to be more obvious, but I guess this is still pretty good. Closing.
