### ISSUE TITLE
Papa Roach - Time Is Running Out

### ISSUE THREAD

**Issue by LostChris894** [YARC-Official/YARG#664]
The Harmonix chart of Time Is Running Out is not working on Clone Hero. I tried to load up the song but unfortunately it is errored and can't work onto YARG. I would love to play it on Vocals so I can get 20/20 FCs out of the Rock Band Track Pack Vol. 2

**Comment by LostChris894** [comment]
https://youtu.be/gOV4VdCsjFA

**Comment by EliteAsian123** [comment]
Can you send the game logs?

> Windows: `C:\Users\<you>\AppData\LocalLow\YARC\YARG`
> You can get here quickly by pressing `Windows Key + R` then typing in `%userprofile%\AppData\LocalLow\YARC\YARG`

If it doesn't work on YARG nor Clone Hero, I'm assuming that the chart is unfortunately corrupted or not formatted correctly.

**Comment by LostChris894** [comment]
It works on Clone Hero
    On Sunday, 4 February 2024 at 17:12:39 GMT, EliteAsian ***@***.***> wrote:  
 
 


Can you send the game logs?


Windows: C:\Users\<you>\AppData\LocalLow\YARC\YARG
You can get here quickly by pressing Windows Key + R then typing in %userprofile%\AppData\LocalLow\YARC\YARG


If it doesn't work on YARG nor Clone Hero, I'm assuming that the chart is unfortunately corrupted or not formatted correctly.

**Comment by LostChris894** [comment]
It's working now thanks
