### ISSUE TITLE
Bug: Flirtin' With Disaster Vocals

### ISSUE THREAD

**Issue by LostChris894** [YARC-Official/YARG#681]
My game stopped and lost it's progress on the song. And I lost track of my awesome ratings.

**Comment by EliteAsian123** [comment]
Hi, can you please provide more info? What happened, and what do you mean by “my game stopped”? Does it happen all of the time for this song, or did it only happen once?

Assuming you meant that your game crashed, and you lost your progress; yes, unfortunately, YARG does not save when you're half-way through a song.

**Comment by RileyTheFox** [comment]
Closing as stale and lack of details regarding the issue
