### ISSUE TITLE
Growing Delay in Vocals Over Time (Stable Build)

### ISSUE THREAD

**Issue by Can1Cyp2** [YARC-Official/YARG#689]
### Description:
I've noticed that the longer the YARG app is open, the longer the delay gets when singing. At first the delay will be minuscule, I sing and I hear myself almost instantly. Then, as the app stays open the delay increases.  I searched online to see if anyone had spoken of the issue and I saw a few people on the YARG Reddit agreeing with me (here: https://www.reddit.com/r/yarg/comments/1amtkhi/vocals_have_massive_delay/).

### Steps to Reproduce:
1. Open the YARG app, Stable Build.
2. Start singing.
3. Keep the app open for an extended period, say ten to twenty minutes.
4. Notice the increasing delay in the singing feature. What was once instant feedback is turned into almost half a second or so of delay.

### Expected Behavior:
The app should maintain a consistent delay regardless of how long it has been open.

### Actual Behavior:
A noticeable delay in hearing vocals from the microphone through the app and it increases the longer the app is open.

**Note:** I have read and understood the contribution guidelines, though this is my first issue on this project so apologies for any errors. This issue is unrelated to any external libraries or assets and is not a duplicate issue (as far as I can tell).

**Comment by RileyTheFox** [comment]
Does the delay increase as you play different songs? Or by "keep the app open" do you just mean sitting there doing nothing? I thought I had fixed this issue temporarily by clearing the vocal monitoring buffer once the song loads but it seems people are still having issues.

And just to confirm this only affects the monitoring? Vocals registering to notes aren't delayed?

Sorry for the delayed response

**Comment by Can1Cyp2** [comment]
No worries, I took a delay myself. My apologies. 

I have experienced delays doing both, keeping the app open doing nothing and by playing songs. It seems this issue does not happen on my laptop though, only my desktop. Pretty weird. It only affects the voice monitoring, the notes are fine.

**Comment by RileyTheFox** [comment]
@Can1Cyp2 Hey sorry for not checking on in this for a while. More audio changes have been made in the past month or so, so I'm wondering if this is still a problem? Thanks!

**Comment by RileyTheFox** [comment]
Closing as stale and I have not heard about this problem in a while. Tag me to reopen this or create a new issue referencing this one if the problem persists
