### ISSUE TITLE
After upgrading to the latest cava, it can no longer be used normally. Operating SystemArch Linux

### ISSUE THREAD

**Issue by wo2ni** [YARC-Official/YARG#696]
![image](https://github.com/YARC-Official/YARG/assets/71865642/612a904a-7bb1-4f58-bd4b-44b63e67e73a)

**Comment by RileyTheFox** [comment]
Can you elaborate on what the issue is?

**Comment by RileyTheFox** [comment]
Closing as stale and lack of information as to what this means
