### ISSUE TITLE
Duplicate songs

### ISSUE THREAD

**Issue by LostChris894** [YARC-Official/YARG#702]
I have 3189 songs and some of them are duplicates. May you please add in a (Remove duplicate songs) option for the song settings where we scan our songs? Cheers.

**Comment by vinaykapadia** [comment]
When you go to the folder list, there is a setting to ignore duplicates.

**Comment by RileyTheFox** [comment]
Not sure what the request was here but as vinay mentioned, there is a setting which will hide duplicates (only if the charts match exactly however)

If the request was to add an option to *delete* your duplicates for you, this will never happen. YARG will never modify a user's song folder.
