### ISSUE TITLE
Problems with YARG stable

### ISSUE THREAD

**Issue by LostChris894** [YARC-Official/YARG#726]
My message says when loading YARG stable is:

"Failed to start YARG. Is it installed?\nOs { code: 2, kind: NotFound, message: \"The system cannot find the file specified.\" }"

**Comment by EliteAsian123** [comment]
Try uninstalling and reinstalling stable YARG. Your settings and other data will not be lost.

**Comment by RileyTheFox** [comment]
Closing as stale
