### ISSUE TITLE
Longer section titles in music menu

### ISSUE THREAD

**Issue by rk-exxec** [YARC-Official/YARG#753]
Hey, I was wondering if you could allow for longer section titles to be viewed properly.
Right now they are cut short relatively early.

![image](https://github.com/YARC-Official/YARG/assets/40037381/9ff2ab32-0210-4330-ac85-3852a4d61ee4)

I tinkered a bit with the SongView Prefab, to maybe find an easy solution but it didn't work out that well:
I added flexible width for the primary text and minimum text width for the other elements, so these fields keep their original width.  
When used as section header, the other fields not enabled and the primary text can expand to whole width, allowing for longer playlist titles.
This comes at the cost, that the artist is now more to the right, as you can see here.

![image](https://github.com/YARC-Official/YARG/assets/40037381/af3aa235-6462-4343-ba71-8f8989d95145)

**Comment by kaduwaengertner** [comment]
The problem with that is that we use the right side to display scores/stars so this would cause another problem

![image](https://github.com/YARC-Official/YARG/assets/87105274/27809197-bae8-4b96-a4d3-eb6529e4312b)

So this would have to be a different prefab to not affect the song items

**Comment by rk-exxec** [comment]
Do you currently have the capactiy to do that or can I give it a try?
I'd like to start contributing to this project a little.

**Comment by EliteAsian123** [comment]
Go ahead!
