### ISSUE TITLE
Feature Request: Library Navigation Suggestion (Jumping through headers)

### ISSUE THREAD

**Issue by Angstdiscord** [YARC-Official/YARG#755]
Navigating large libraries is kinda slow.

When sorting by something like artist, it would be nice if you could quickly jump between the different artist headers.

This way I could have an artist with a large amount of songs but skip that artist with a single tap.

**Comment by Angstdiscord** [comment]
Actually, seems like this feature already exists here 
https://docs.yarg.in/en/songs

However I don't have a yellow fret option in the menu here. nor does my yarg give me the option to hold the orange fret to get anything other than the other options menu

**Comment by poliwhirlge** [comment]
> Actually, seems like this feature already exists here https://docs.yarg.in/en/songs
> 
> However I don't have a yellow fret option in the menu here. nor does my yarg give me the option to hold the orange fret to get anything other than the other options menu

The screenshot on that page is either old or a concept, right now to go between artists you can hit orange to go to the menu, then select "go to section" and scroll down the list. Menus/navigation aren't final and improvements are planned.

**Comment by Angstdiscord** [comment]
Yeah, it looks like this feature existed in version 11., but was changed in 12. I see newer wip builds on twitter that seemingly brought the feature back, so I'll be patient and wait for the update. Thank you for the response.

**Comment by Angstdiscord** [comment]
This was fixed in #756
