### ISSUE TITLE
Crash at startup in Linux

### ISSUE THREAD

**Issue by Yokox1** [YARC-Official/YARG#761]
I'm on Fedora 40 trying to start the game, but it crashes at the screen that says "Loading song resources... Downloading new version...".  This happens with stable and nightly.   

The terminal shows this:
```
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
[1]    104290 segmentation fault (core dumped)  ./YARG
```

This is the [Player.log](https://github.com/YARC-Official/YARG/files/15205973/Player.log) file  

And this is the content of my boot.config file:
```
gfx-enable-gfx-jobs=1
gfx-enable-native-gfx-jobs=1
wait-for-native-debugger=0
hdr-display-enabled=0
gc-max-time-slice=3
```

**Comment by EliteAsian123** [comment]
This looks like a Unity issue, and we cannot update the Unity version we are using right now since doing so breaks Xbox guitars. Very unfortunate.

There may be something that can be done, but I'm not too experienced with Linux. Sorry for the inconvenience.

**Comment by Yokox1** [comment]
I understand. Hopefully, this could get fixed in the future. I guess I'll be booting Windows to play in the meantime 😅  Thank you for the clarification!

**Comment by EliteAsian123** [comment]
Hello again! It appears that there was a [similar bug report on our Discord](https://discord.com/channels/1086048856678084609/1240991389240659979) which found the exact problem.

Turns out it's a problem in the kernel in Fedora 40. Apparently, rolling back to Fedora Linux 39.20240505.0 and kernel version 6.8.8-200.fc39.x86_64 can work. Along with this, the bug within the kernel has been patched but not yet released (might not be since this was a while ago, but not sure), so hopefully it's fixed soon!

**Comment by Yokox1** [comment]
Hello!  
I apologize for the delayed response. Since I opened this issue, there have been several kernel updates, but none resolved the problem. However, today, Fedora released the 555 version of the Nvidia Drivers for Linux. I can confirm that this update has fixed the issue, the game no longer crashes at startup and I can play without any problems!  
Thank you very much!

**Comment by EliteAsian123** [comment]
Nice! Glad you got it working :)
