### ISSUE TITLE
Request: make albums not be case sensitive

### ISSUE THREAD

**Issue by KawaiiTemDev** [YARC-Official/YARG#765]
# Example:
![image](https://github.com/YARC-Official/YARG/assets/25987110/5b5a92a2-4ad3-44f8-82b2-12c52f0ec316)

These are both the same album, but due to the difference in case (with the artist) they are not merged.

**Comment by vinaykapadia** [comment]
Might have already been fixed. Looks fine to me on the nightly build. I have two albums with just the casing different, it combines them fine.

**Comment by vinaykapadia** [comment]
Ah I see it. It works fine if you sort by Artist or Album, but not if you sort by Artist-Album. Will fix.
