### ISSUE TITLE
Background Video Only Working For Certain Songs

### ISSUE THREAD

**Issue by MaliciousNine** [YARC-Official/YARG#768]
Bug is pretty self explanatory. I noticed that a song (The Denny's Grand Slam from CSC's "The" Pack) had its BG video work fine, but another (About a girl but every time it hits a high note it slows down from Chezy's CHARTS) doesn't. Looking closer, the former was originally a webm while the latter was originally an MP4. And in general, backgrounds that were packed with songs tend to not display more often than not either. Dunno what's going on here.

Linux build, RTX 3070, Kernel 6.8.0, Nvidia 550, 32GB RAM, i5-12600KF

**Comment by sonicfind** [comment]
Unity does not support mp4 on Linux. Nothing we can do about that at the moment.
