### ISSUE TITLE
YARG scan all computer at launch. MAC

### ISSUE THREAD

**Issue by elouannd** [YARC-Official/YARG#769]
When I launch either Stable or Nighly. YARG start to scan the entire computer, which is taking forever . Is there a way I could reset the setting?

**Comment by EliteAsian123** [comment]
You should be able to delete the settings file at `~/Library/Application Support/YARC/YARG/release/settings.json` which will reset all of the settings.

**Comment by elouannd** [comment]
Yep it worked Thanks!
