### ISSUE TITLE
Titles that begin with "The" should not be listed under "T"

### ISSUE THREAD

**Issue by BenMcLean** [YARC-Official/YARG#793]
Ideally, you want [natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order) with this one exception for "The" (ideally case insensitive) because otherwise you end up with half the titles in the world under "T".
This goes for song titles, band names, album names, everything.

**Comment by EliteAsian123** [comment]
Hello! This was fixed as of the latest nightly build. Thanks for the report!
