### ISSUE TITLE
Guitar Hero Chart Bugs

### ISSUE THREAD

**Issue by FanGamer96** [YARC-Official/YARG#807]
Two errors are present when playing the charts from the Guitar Hero games. First, the unpitched vocals are not detected as vocals and do not require any input from the player. Second, the guitar bots miss on random occasions, but I am unsure why that is. The video shows the first few seconds of Metallica's Fuel from Guitar Hero Metallica with 5 bots playing Lead Guitar, 5-lane Drums, Bass Guitar, Rhythm Guitar, and Vocals. Also, despite showing footage from the latest Nightly build, these bugs are also present on the most recent stable build.

https://github.com/YARC-Official/YARG/assets/173211035/6c377cb2-767c-4971-9da9-30a96ff5944d

**Comment by sonicfind** [comment]
The lack of talkies are due to bad rips. They are missing very important data that would make them playable. Nothing we can do on our end.
The bot missing issue is known.

**Comment by RileyTheFox** [comment]
Closing as the first problem is beyond our control, and the second issue is fixed for v0.13 when that releases
