### ISSUE TITLE
Recommended com.unity.localization Update

### ISSUE THREAD

**Issue by jbienz** [YARC-Official/YARG#811]
Today I started working with the codebase on a feature I might PR. When I first opened the project and played the game, everything worked fine. But when I exited play mode and tried to start again I started getting the error:

> Attempting to use an invalid operation handle

This error appeared several times and I could not get the game to function properly again.

After searching for the above error message, I came across [this thread](https://forum.unity.com/threads/localization-exception-attempting-to-use-an-invalid-operation-handle.1398928/) where a Unity employee recommended upgrading the **com.unity.localization** package to version **1.4.3**. Note that this was recommended _even though Package Manager does not show it as supported_ in 2021.3.36.

I did manually update the package to **1.4.3** by editing manifest.json and the Invalid Operation Handle errors went away.

I don't know how long YARG will remain on 2021.3.36, but the Unity employee in that thread mentioned a lot of fixes and recommended upgrading this package. If nothing else, at least this might help someone else running into the same problem.

**Comment by EliteAsian123** [comment]
We are actually going to completely remove the package and roll out our own localization system quite soon (see the `localization` branch). This will mean this package will be removed entirely so this problem shouldn't persist once merged.

**Comment by TheNathannator** [comment]
Yeah, we've found it rather annoying to work with for our purposes. The translations are inconvenient to edit, sometimes the saved files change in much more significant ways than they really need to, and actually getting the translated strings has too many layers to it.

No one else seems to have run into this issue before, weird that it's happening to you lol.

> I don't know how long YARG will remain on 2021.3.36

We're currently stuck on 2021.3, as 2022 removed proper XInput support for the input system and switched to Windows.Gaming.Input internally, which doesn't support any of the Xbox 360 instruments. We won't be able to upgrade until we implement a replacement backend or find a way to make it switch back over.

**Comment by jbienz** [comment]
Cool! Sounds like this particular issue will hopefully go away with the refactor then. I'll go ahead and close this since it won't be updated in this particular way. It should still show up in search if anyone comes looking for that particular error message.
