### ISSUE TITLE
No video background on songs (Linux)

### ISSUE THREAD

**Issue by 8D1** [YARC-Official/YARG#817]
![image](https://github.com/YARC-Official/YARG/assets/28695187/7fb08950-efe6-4004-b95e-60f3297b674c)
OS: Gentoo linux Dist Kernel 6.6.32, W/ KDE plasma 6.1.2

**Comment by RileyTheFox** [comment]
Only vp8 encoded webm video files are supported on Linux per Unity's limitations. Please ensure the video you're trying to use is in the correct format

**Comment by 8D1** [comment]
That explains it, Thanks anyways mate!
