### ISSUE TITLE
Request: Choose difficulty per song section

### ISSUE THREAD

**Issue by BallistiX09** [YARC-Official/YARG#834]
I'm not sure how doable this would be, but it's an idea I've had in mind all the way back since Rock Band 3. There's some songs I can handle fine on expert for the majority of the songs, but then it'll get to something like a solo where it just becomes absolutely insane, where I pretty much need to resort to hitting randomly and hoping for the best. I'm not fussed about scores all that much so that's not a big issue, but it does ruin the vibe though.

I know I could just practice that one section over and over again in hopes of learning it, but I'm way too casual of a player personally to put that much time into it. It would be amazing if you could set an advanced difficulty preset for a song, where it'll ask for a default difficulty and then show the sections of the song (I'm sure I've seen that as a thing but I might be wrong), letting you override the difficulty track for each section manually.

That way, in gameplay, it'll dynamically switch to the other difficulty level for that one section (or as many as you choose to override), and then revert back to whatever the default level is. There might be some songs where the transition isn't perfect, but I'd imagine most song sections happen at breaks in patterns anyway, so I doubt it would be too much of an issue.

**Comment by RileyTheFox** [comment]
Going to close this as not planned. This would be a lot of work to do for something very few people would use. You're better off just practicing a whole lower difficulty then moving up when ready.
