### ISSUE TITLE
Request: always choose the highest difficulty 

### ISSUE THREAD

**Issue by iloveicedgreentea** [YARC-Official/YARG#888]
First of all, I love YARG thank you for all you do for the community. This is miles ahead of clone hero and truly a one of a kind project. It has rocketed my drum skills forward and I also have a lot of fun using it

it would be nice to be able to have a setting to always select the highest difficulty by default. I notice, almost randomly, songs will default to expert when I previously selected expert+ before. It’s hard to discover when a song has expert+ so I pretty much have to check every song before I start. A toggle switch for this would be nice

**Comment by sonicfind** [comment]
If you select Expert+ on a song, and the next one sets to expert, that's simply because it doesn't *have* expert plus. So long as you don't manually select Expert in the difficulty screen, it will auto-select Expert+ when its available.

**Comment by iloveicedgreentea** [comment]
So you’re saying all I need to do is just select expert+ and then leave it alone so it will always attempt to select it again when a song has it? Seems like when I go to check, it overwrites the last selected because it doesn’t have expert+

**Comment by sonicfind** [comment]
yes, just leave it alone **after** selecting X+ on a song that has it.
