### ISSUE TITLE
Save profile and or player data to file/files

### ISSUE THREAD

**Issue by Alfredoes234** [YARC-Official/YARG#890]
Currently I am unable to find where the profile/played data lives and I feel it would be cool if there was a way to save the profile as a file so that it can be backed up and downloaded on another PC.

**Comment by kaduwaengertner** [comment]
The files are already saved in a way that you can backup, you can find all files in
Windows: C:\Users\YourUsername\AppData\LocalLow\YARC\YARG
Mac: ~/Library/Application Support/YARC/YARG
Linux: ~/.config/unity3d/YARC/YARG
